### ISSUE TITLE
Encryption routine is ineffective on Japanese text etc.

### ISSUE THREAD

**Issue by qntm** [qntm/scp-3125#2]

**Comment by MrNonSequitur** [comment]
Could you elaborate?

**Comment by qntm** [comment]
The purpose of the encryption step is to make it so that readers cannot simply hit "View source" to bypass the keypad. However:

```
> var owtns = require("./src/js/owtns.js");
undefined
> owtns.encrypt("abcde");
'oxvqw'
> owtns.encrypt("ファイル終了");
'ファイル終了'
```

the routine has no effect on Japanese text, it just returns the original text again.

**Comment by MrNonSequitur** [comment]
Is this a deeper problem than just needing an ordering of characters? Could you just use Unicode (sans U+0000) and never normalize it? (Or alternatively, write out the codepoints as numbers after manipulation)

**Comment by qntm** [comment]
I can certainly hold off on normalization but I can't guarantee that Wikidot or other consumers of the output text won't do the same.

Abandoning this "character rotation" approach and writing out code points as numbers, or maybe just using Base64, seems like it might be the only option.

**Comment by MrNonSequitur** [comment]
Well, you could still rotate the codepoints, you just couldn't write them as literal characters after doing so, until you rotate them back.

**Comment by qntm** [comment]
I have to write them as literal characters to submit the encrypted article to Wikidot.

**Comment by MrNonSequitur** [comment]
Ah, sorry, I was too vague; you couldn't write the rotated characters out _directly_ as literal characters, but you could write them out in a more indirect manner, such as in base64.

**Comment by qntm** [comment]
Solved using percent-encoding. (Base64 has some [troublesome properties](https://developer.mozilla.org/en/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_.22Unicode_Problem.22) when applied to Unicode strings.)

```
> var owtns = require("./src/js/owtns.js")
undefined
> owtns.encrypt("ファイル終了");
'%A3%83%95%C3%82%R1%U3%82%C4%O3%83%SI%S7%H5%82%B4%JO%86'
```
